fix graphql token is async
silverlogic/baseapp-frontend pull request #86
Opened 2024-02-23 23:36 UTC by nossila

2024-02-28 11:31 UTC, anicioalexandre approved these changes

2024-03-06 12:54 UTC, anicioalexandre requested changes
can we version the packages @nossila ?

2024-03-06 19:40 UTC, ficast approved these changes

2024-03-06 19:43 UTC, anicioalexandre approved these changes

2024-03-06 19:43 UTC, merged